shellEmulator: true
trustPolicy: no-downgrade
minimumReleaseAge: 10080
blockExoticSubdeps: true
packages:
  - docs
onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
peerDependencyRules:
  allowAny:
    - eslint
