minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade

peerDependencyRules:
  allowAny:
    - eslint

shellEmulator: true

packages:
  - docs

allowBuilds:
  esbuild: true
  simple-git-hooks: true
