name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout e18e repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use pnpm and node
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0

      - name: Lint
        run: pnpm lint
